name: "Build"

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: PHP ${{ matrix.php }} with ${{ matrix.dependencies }} deps
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      max-parallel: 8
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php:
          - "8.1"
          - "8.2"
          - "8.3"
        os:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: none
          php-version: "${{ matrix.php }}"
          ini-values: memory_limit=-1

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Run psalm"
        run: vendor/bin/psalm

      - name: "Run phpunit"
        run: vendor/bin/phpunit

      - name: "Run phpbench"
        run: vendor/bin/phpbench run
